### ISSUE TITLE
No routing grade 4, 5 bike paths possible in the osrm demo server.

### ISSUE THREAD

**Issue by 0709wiwiwi** [fossgis-routing-server/cbf-routing-profiles#10]
Subject.
https://github.com/fossgis-routing-server/cbf-routing-profiles/blob/master/bike.lua
Surely someone can or will adjust bike.lue in such a way that routing over grade 4 or 5 is also possible ? 
With the current settings, it is completely impossible to route over these paths even by placing additional extra Via Points.
Now, very decent legally allowed and usually even very nice simple to ride paths are totally excluded from the (demo) online routing results.

**Comment by datendelphin** [comment]
As other people have pointed out, we only have the option of a single bike profile for the demo server (limited capacity). Bikes are notorious for the extremely broad spectrum of acceptable roads. We aim for an unskilled, relatively small tired cyclist.
That there is an official bike trail is not surprising, given the broad spectrum. Here we have mountain biking trails, which also wouldn't be covered by this particular routing profile.
grade 4 and higher are at least "mostly soft" which means to me bike tires will sink in in wet conditions. If there drove bikers in wet condition, it will be unusable even in dry conditions. If it remains usable, maybe it was a higher grade after all.

Anyway. This is only a demo profile. It can't cover everything. I'm not sure including 4 and 5 is the right choice

**Comment by 0709wiwiwi** [comment]
Understand that making a general choice can be a problem. Moderately wet conditions don't bother me that much, if it's too bad I'll drive around. An odd demo that shows so not a flexible but a stubborn router. Or maybe is it meant to not overuse the service?
