### ISSUE TITLE
Whitelist rolled kerbs for cars

### ISSUE THREAD

**Issue by osmuser63783** [fossgis-routing-server/cbf-routing-profiles#16]
See https://github.com/Project-OSRM/osrm-backend/issues/6582

This is a rolled kerb: 
![Rolled_curb_on_a_residential_driveway](https://github.com/fossgis-routing-server/cbf-routing-profiles/assets/127188803/cd4dfbcd-9190-4486-9e48-92dda02341b2)
(Photo [Rolled curb on a residential driveway](https://commons.wikimedia.org/wiki/File:Rolled_curb_on_a_residential_driveway.jpg) by [Streetsweeper](https://www.flickr.com/people/29053105@N04) licensed [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/deed.en))

Cars can drive over it, so it should be whitelisted as a "flat kerb" like `flush` and `lowered`.

**Comment by datendelphin** [comment]
Looks good, thanks. It will take a while until it is deployed. I'll close the issue once it is deployed on routing.openstreetmap.de
