### ISSUE TITLE
Discrepancies OSRM

### ISSUE THREAD

**Issue by iaroslavzif** [fossgis-routing-server/cbf-routing-profiles#18]
Hello!

I have this way https://www.openstreetmap.org/way/131391897. 
According to ORSM Debug tool the routing should happen. https://map.project-osrm.org/debug/car.html#17.2/49.99506/36.27708
But actually is not working:[ ](https://map.project-osrm.org/?z=18&center=49.995273%2C36.278189&loc=49.995864%2C36.278620&loc=49.994764%2C36.275171&hl=en&alt=0&srv=0)

Can be there a bug or something like this? 

Thank you!

**Comment by osmuser63783** [comment]
Two points
1. Does the debug tool you linked to use the routing profile in this repository? I would have thought it uses the routing profile at https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua
2. The way is tagged smoothness=horrible which is probably why the routing profile assumes a very low speed, this can be seen in the debug tool. And this is probably why it avoids the road.

I'm not a maintainer, just another user who stumbled across your report!

**Comment by iaroslavzif** [comment]
Hello!

You might be right. 
Looking at the time for when routing on the road and when not routing on the road, we can see the time differences. 

Good point!

![Captură de ecran din 2024-09-13 la 09 27 45](https://github.com/user-attachments/assets/35394852-3acb-4a78-9103-465809c0e75c)
![Captură de ecran din 2024-09-13 la 09 27 50](https://github.com/user-attachments/assets/78e6260c-ca73-466e-b03f-170493d577b7)

**Comment by datendelphin** [comment]
Yes that is the penalty for the bad surface. Any questions in that regard? Or can we close this issue?

**Comment by iaroslavzif** [comment]
You can close it. 
Thank you!
