### ISSUE TITLE
Control for key sac_scale

### ISSUE THREAD

**Issue by hungerburg** [fossgis-routing-server/cbf-routing-profiles#9]
I am writing because of this, https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=47.8040%2C13.6767%3B47.8343%2C13.6897 - I came here via https://routing.openstreetmap.de/about.html

Openstreetmap data contains a sizeable number of hiking trails. Lots of those paths are tagged with https://wiki.openstreetmap.org/wiki/Key:sac_scale - a compound measure, to assess the prerequisites afforded, to turn the hike into a pleasant adventure. Especially trails graded _alpine_hiking_, _demanding_alpine_hiking_, _difficult_alpine_hiking_ need upfront preparations, that make them unsuitable for casual use, like when doing a search for a route from the hut to the parking.

I'd say, nobody will be harmed, if such paths were skipped in OSRM results. Users who seek them will still find them. Maybe, the easiest would be, to just drop those in the import stage? Some quick overpass turbo searches in my local area suggest, that the mapping community is using the tags quite concisely and can be trusted.

**Comment by georg-d** [comment]
-1 for simply dropping them during import because that means it is completely impossible to get routed over those paths – but some places cannot be reached by different ways, which would be bad for a router in our "main entry door" https://www.openstreetmap.org/directions

+1 to allow users to choose/control what grade of SAC hiking scale is acceptable. Either as two seperate profiles (e.g. foot and alpine hiker) or by a dedicated setting like in [Valhalla](https://valhalla.openstreetmap.de/). Default setting may be 1 like in Valhalla or 2, because John Doe will still manage those.

**Comment by datendelphin** [comment]
We don't have the capacity currently to run more profiles. For OSRM it might be better to drop them for now, until there would be a facility to warn the user explicitly.

**Comment by hungerburg** [comment]
Being told, that there is no space for profiles, and having gone through a proposal upstream, that aimed to spare fossgis-routing-server controlling for sac_scale, what remains, looks like dropping anything sac_scale=*alpine* is the only way to keep  openstreetmap suggesting itineraries, that may contain UIAA II scrambles. I do not know, whom this aims at, but e.g. amongst in the Rax area, the shortest way from the hut to the parking lot might no be the one most appropriate?

**Comment by hungerburg** [comment]
0 speed should make the journey endless. Tested this - https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=47.2932%2C11.3433%3B47.3051%2C11.3503#map=15/47.2959/11.3491 - Do not know anybody who could achieve this in 34 minutes. I'd say 999 of 1000 OSRMF users will just turn around where the arete starts ;) Maybe

```
      sac_scale = { hiking = 0.5,
                    mountain_hiking = 0.3,
                    demanding_mountain_hiking = 0.1,
                    alpine_hiking = 0,
                    demanding_alpine_hiking = 0,
                    difficult_alpine_hiking = 0
```
Shifting starting point some meters south, looks like only distance counts.

**Comment by hungerburg** [comment]
Let me elaborate a bit: The sac_scale key has six values with difficult_alpine_hiking a.k.a. T6 being top value. It is appropriate for the path linked in the first post.

On the other hand, the low anchor, hiking a.k.a. T1 is for paths, that pose no problems for average persons: Not steep, surface unpaved ground, but no obstacles. Nothing to slow one down by much. No orienteering difficulties. Using elevation data good enough to account for ascents.

**Comment by datendelphin** [comment]
I see. That was a bug introduced with the separate weights. Fixed in https://github.com/fossgis-routing-server/cbf-routing-profiles/commit/2daa6d884a66d43525f2e3f99028f449efe64305
I would rather not include mountain hiking in the generic foot profile, as that would require appropriate shoes.

**Comment by hungerburg** [comment]
Great! Ordinary sneakers are good enough for mountain_hiking. But I wont complain. Only one wish left: Please add **`difficult_alpine_hiking`** to the list of values in sac_scale test.

It is not a tagging error on the site from link1, see  https://wiki.openstreetmap.org/wiki/Key:sac_scale

**Comment by datendelphin** [comment]
right, the T6 one. Sure

**Comment by hungerburg** [comment]
From my point of view, the OSRM profile on osm.org works as designed. I do not see a reason to keep this issue open any longer.
